void inputArray(int *arr,int n);
void outputArray(int *arr,int n);
int minimo(int *arr,int n);
void selectionSort(int *arr,int n);
void insertionSort(int *array, int size);
void insertSortedArray(int *array, int *size, int element);
void bubbleSort(int *arr,int n);
int adaptiveBubbleSort(int *arr,int n);
int ricercaBin(int *arr, int n, int element);
int ricercaord(int *arr, int n, int element);
